name: 🚀 Deploy Next.js App

on:
  push:
    branches:
      - main   # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 🚀 Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          
          cd D:/LiveProject/NEXT_JS_WEB_JIVO.IN

          echo "🛑 Stopping PM2..."
          pm2 stop jivo-web

          echo "📥 Pulling latest code..."
          git pull

          echo "📦 Installing dependencies..."
          npm install

          echo "🧹 Cleaning old build..."
          if exist .next rmdir /s /q .next

          echo "🏗️ Building project..."
          npm run build

          echo "📂 Copy static files..."
          xcopy .next\static .next\standalone\.next\static /E /I /Y
          xcopy public .next\standalone\public /E /I /Y

          echo "🚀 Starting app..."
          pm2 start ecosystem.config.js
          pm2 save

          echo "🎉 Deployment Done!"
          exit
          EOF